### ISSUE TITLE
Star Voting Runtime Exception

### ISSUE THREAD

**Issue by illegalprime** [illegalprime/pollparty.io#3]
```
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: [[{"1", 8}, {"0", 5}]]
        (vote 0.1.0) lib/vote/voting/star.ex:21: Vote.Voting.Star.do_runoff/2
        (vote 0.1.0) lib/vote/voting/star.ex:12: Vote.Voting.Star.tally/2
        (vote 0.1.0) lib/vote/voting/lib.ex:70: Vote.Voting.tally/3
        (vote 0.1.0) lib/vote_web/live/results_live.html.leex:6: anonymous fn/4 in VoteWeb.ResultsLive.render/1
        (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
        (vote 0.1.0) lib/vote_web/live/results_live.html.leex:4: anonymous fn/3 in VoteWeb.ResultsLive.render/1
        (phoenix_live_view 0.17.7) lib/phoenix_live_view/diff.ex:387: Phoenix.LiveView.Diff.traverse/7
        (phoenix_live_view 0.17.7) lib/phoenix_live_view/diff.ex:494: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
```

**Comment by illegalprime** [comment]
update: the bug only appears if there are two or less options in STAR voting, and does not affect any results (other than crashing)
